receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, otlp, debug]
